language: rust
rust:
  - stable
  - beta
  - nightly
deploy:
  provider: cargo
  token:
    secure: MriEv0AVNHSRIqo5sU8WKIaCkm3R3z4HYwPhGIj5AwdyNoW8DqoRKW77Q7sO6a9JFwY8J8SQ8wARcYTjXJB97WqjrfWIXvHCk+1PXWBCBw09jaZhemxQiQwnbj3hE9QX4JVsRa4fHhGlfTX+41HlFkUvYCP9iprd17wMPGdDHo2nzJ+ELfJ7AuD7bWJiCrwS4qynQk3mW7oT4D1NSDgAMMHhNO3VGKabnhEX/F/hqNaGhDUANr9FWE8QkkWs5KpUtbM04DDloyMuTX5QwJbZtO94YUKL7NGRqa3yAfEQuDd9cbhNgzpRdNEDnB3/qkmtxHonnrUYzVRYfg5tXwv9sjYyQV/rctk8SduoqdVl9y0Upl4QgLmCO0oyVmhDuM+YVHpZGu8gwSfNAg0Gax6IEgeG/z6jE4uhWvUPZ3s4nk1R6xwdIeHBuSlUKJFLkBEpwMqhLwHordDbRqCvmG1EY8zJobET3MO7yZlsb9eW/Vs2LJlL81eP7R93j2HKarJaW1dTmnEQEzvDuVVK4rMdawkbtZ953IU+wHFrqOD31Y+/MUs2ZZtzf/771BxvyiB1D0tM8fD78vJIb+imDtXTUoa1iNLv0bQQHeBStWL9oxDTikYWItSSVWyRn8EfRpZCbqoNHEPuAbqxxGrAJhUd6dVDrnRjwp+Ap8CToLJRrjQ=
  on:
    tags: true
    all_branches: true